version: '3.8'

services:
  react-app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: react-app
    ports:
      - "3000:3000"
    networks:
      - react-network

  nginx:
    image: nginx:latest
    container_name: nginx-server
    ports:
      - "80:80"
    networks:
      - react-network
    depends_on:
      - react-app
    volumes:
      - ./nginx.conf:/etc/nginx/conf.d/default.conf
      - ./build:/usr/share/nginx/html

networks:
  react-network:
    driver: bridge
